name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia 00:00 UTC
  workflow_dispatch:       # permite rodar manualmente

permissions:
  contents: write          # necessário para publicar na branch 'output'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: IsabelCasPe
          outputs: |
            dist/snake.svg

      - name: Publish to GitHub Pages (branch output)
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

